-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `role` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Event` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `date` DATETIME(3) NOT NULL,
    `location` VARCHAR(191) NOT NULL,
    `budget` DOUBLE NOT NULL,
    `description` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Asistentes` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `country` VARCHAR(191) NOT NULL,
    `eventId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AlergenoAsistente` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `asistenteId` INTEGER NOT NULL,
    `alergeno` ENUM('MILK', 'EGGS', 'FISH', 'CRUSTACEAN_SHELLFISH', 'TREE_NUTS', 'PEANUTS', 'WHEAT', 'SOYBEANS', 'SESAME', 'MUSTARD') NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Menu` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `eventId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Plato` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `isVegan` BOOLEAN NOT NULL,
    `isGlutenFree` BOOLEAN NOT NULL,
    `menuId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `IngredientePlato` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `platoId` INTEGER NOT NULL,
    `ingrediente` ENUM('TOMATO', 'CHEESE', 'LETTUCE', 'CHICKEN', 'BEEF', 'ONION', 'GARLIC', 'PEPPER', 'SALT', 'OLIVE_OIL', 'BUTTER', 'CARROT', 'POTATO', 'RICE', 'PASTA', 'MILK', 'EGG', 'FLOUR', 'SUGAR', 'APPLE', 'BANANA', 'STRAWBERRY', 'ORANGE', 'SPINACH', 'BROCCOLI', 'CUCUMBER', 'ZUCCHINI', 'CORN', 'PEAS', 'MUSHROOM', 'BASIL', 'CILANTRO', 'THYME', 'ROSEMARY', 'PARSLEY', 'LEMON', 'LIME', 'GINGER', 'CINNAMON', 'HONEY', 'VINEGAR', 'SOY_SAUCE', 'YOGURT', 'CREAM', 'BACON', 'HAM', 'SHRIMP', 'SALMON', 'TUNA', 'ALMOND', 'WALNUT', 'PISTACHIO', 'OREGANO', 'CHILI_PEPPER', 'TURMERIC', 'CUMIN', 'CORIANDER', 'CLOVES', 'BAY_LEAF', 'MUSTARD_SEED', 'FENNEL', 'ANISE', 'MINT', 'COCONUT_MILK', 'LENTILS', 'CHICKPEAS', 'AVOCADO', 'PINEAPPLE', 'BELL_PEPPER', 'SCALLIONS', 'CABBAGE', 'ARTICHOKE', 'ASPARAGUS', 'BRUSSELS_SPROUTS', 'BLUEBERRIES', 'RASPBERRIES', 'WATERMELON', 'PEACH', 'PEAR', 'MANGO', 'KIWI', 'PUMPKIN', 'SWEET_POTATO', 'CAULIFLOWER', 'GREEN_BEANS', 'BLACK_BEANS', 'RED_BEANS', 'QUINOA', 'BARLEY', 'OATS', 'SESAME_SEEDS', 'SUNFLOWER_SEEDS', 'PUMPKIN_SEEDS', 'MAPLE_SYRUP', 'CHOCOLATE', 'WHITE_CHOCOLATE', 'DARK_CHOCOLATE', 'COCONUT', 'CASHEWS', 'MACADAMIA_NUTS', 'RICOTTA', 'MOZZARELLA', 'PARMESAN', 'GOUDA', 'BRIE', 'CHEDDAR', 'PROVOLONE') NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Asistentes` ADD CONSTRAINT `Asistentes_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `Event`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `AlergenoAsistente` ADD CONSTRAINT `AlergenoAsistente_asistenteId_fkey` FOREIGN KEY (`asistenteId`) REFERENCES `Asistentes`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Menu` ADD CONSTRAINT `Menu_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `Event`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Plato` ADD CONSTRAINT `Plato_menuId_fkey` FOREIGN KEY (`menuId`) REFERENCES `Menu`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `IngredientePlato` ADD CONSTRAINT `IngredientePlato_platoId_fkey` FOREIGN KEY (`platoId`) REFERENCES `Plato`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
